name: Firmware

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - esp32
          - esp32-debug
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        
      - name: Select configuration
        run: mv firmware/config/${{ matrix.target }} firmware/sdkconfig

      - name: Compile firmware
        uses: espressif/esp-idf-ci-action@main
        with:
          path: firmware

      - name: Archive artifacts
        run: |
          mkdir -p release
          pushd firmware/build
          zip -r ../../release/build-${{ matrix.target }}.zip .
          popd
          cp firmware/build/zeus.bin release/zeus-${{ matrix.target }}.bin

      - name: Upload raw build output
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.target }}.zip
          path: release/build-${{ matrix.target }}.zip

      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release/**

  release:
    name: Release
    if: github.ref_protected
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Download release artifacts
        uses: actions/download-artifact@v2
        with:
          name: release

      - name: List release assets
        run: |
          ls -lah
          ls -lah release

      - uses: codfish/semantic-release-action@v1
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}